# ラベルの自動付与ルール
frontend:
  - changed-files:
      - any-glob-to-any-file:
          - src/app/**
          - src/components/**
          - src/pages/**
          - '*.tsx'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - convex/**
          - src/api/**
          - src/server/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.spec.ts'
          - tests/**
          - '**/*.test.tsx'
          - '**/*.spec.tsx'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - docs/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
          - yarn.lock
          - pnpm-lock.yaml

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - .gitlab-ci.yml
          - .circleci/**

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.js'
          - '*.config.ts'
          - .env*
          - tsconfig.json
