# .github/labeler.yml
# ラベルの自動付与ルール

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.tsx'
          - 'src/**/*.ts'
          - 'src/components/**'
          - 'src/app/**'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'convex/**'
          - 'src/api/**'
          - 'src/server/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.test.tsx'
          - '**/*.spec.ts'
          - 'src/__tests__/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'pnpm-lock.yaml'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.ts'
          - '*.config.js'
          - 'tsconfig.json'
          - '.eslintrc*'
          - '.prettierrc*'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

feature:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/lib/vibelogger*'
          - 'src/lib/convex-helpers*'
